[build]
  command = "yarn build"
  functions = "api/"

[[redirects]]
  from = "/api/*"
  to = "https://api.airtable.com/v0/:splat"
  status = 200
  force = true
  headers = {Authorization = "Bearer TOML_AIRTABLE_KEY"}

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
